<?php

namespace AppBundle\Entity;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByFilter($filter)
	{
		$queryBuilder = $this->createQueryBuilder('t');

		if(isset($filter['project'])) {
			$queryBuilder->andWhere('t.project_sid = :project_sid');
			$queryBuilder->setParameter('project_sid', $filter['project']->getProjectSid());
		}

		if(isset($filter['todo_status'])) {
			$queryBuilder->andWhere('t.todo_status_sid = :todo_status_sid');
			$queryBuilder->setParameter('todo_status_sid', $filter['todo_status']->getTodoStatusSid);
		}

		if(isset($filter['order_by']) && isset($filter['order_dir'])) {
			$queryBuilder->orderBy('t.'.$filter['order_by'], $filter['order_dir']);
		}

		$query = $queryBuilder->getQuery();

		return $query->getResult();
	}
}
